<?php
// @codingStandardsIgnoreFile

/** @var Snowdog\Menu\Block\NodeType\CategoryChild $block */
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
$categoryId = $block->getContent();
$category = $categoryFactory->create()->load($categoryId);
$children = $category->getChildrenCategories();
$children->clear();
$children->addAttributeToSelect('include_in_menu');
$children->load();
?>

<ul class="mega-menu__children">
    <?php foreach ($children as $child) : ?>
        <?php if ($child->getIsActive() && $child->getIncludeInMenu()) : ?>
            <li><a href="<?= $child->getUrl() ?>" title="<?= $child->getName() ?>"><?= $child->getName() ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>